# 1 control plane node and 2 worker nodes
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name:  chen-k8s-kind
networking:
  serviceSubnet: "10.76.0.0/16"
  podSubnet: "10.77.0.0/16"
nodes:
- role: control-plane
- role: worker
- role: worker
